version: "3.9"

services:
  backend:
    image: backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
    secrets:
      - gemini_api_key
    networks:
      - app-network

  frontend:
    image: frontend
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network

secrets:
  gemini_api_key:
    file: ./secrets/gemini_api_key.txt

networks:
  app-network:
    driver: bridge
